name: build
on: workflow_dispatch

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for other workflows
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install pydocbrowser
        run: |
          python -m pip install wheel
          python -m pip install git+https://github.com/tristanlatr/pydocbrowser.git
      
      - name: Setup pydocbrowser config
        run: | 
          curl https://raw.githubusercontent.com/tristanlatr/pydocbrowser/main/packages.toml > packages.toml
          curl https://raw.githubusercontent.com/tristanlatr/pydocbrowser/main/README.md > README.md

      - name: Build
        run: |
            set +e
            
            # For testing, it will create many jobs, a values more like 200 should be set for production
            python -m pydocbrowser --build-timeout 1

            # Exit code 21 means it stopped generating docs because of the build timeout
            if [[ $? -eq 21 ]]; then
              # Send signal to build docs, again to complete
              curl -XPOST -u "${{secrets.GH_USERNAME}}:${{secrets.GH_TOKEN}}" \
                -H "Accept: application/vnd.github.everest-preview+json" \
                -H "Content-Type: application/json" \
                https://api.github.com/repos/pydocbrowser/pydocbrowser.github.io/actions/workflows/20465935/dispatches \
                --data '{"ref": "main"}'
              exit 0
            elif [[ $? -eq 0 ]]; then
              exit 0
            else
              exit 1
            fi

        shell: bash
      
      - name: Publish main
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          destination_dir: build
          publish_branch: 'main'
          user_name: 'Github Actions'
          user_email: "actions@github.com"
          commit_message: "build"
          enable_jekyll: false
      
      - name: Publish www
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/www
          publish_branch: 'www'
          user_name: 'Github Actions'
          user_email: "actions@github.com"
          commit_message: "build"
          enable_jekyll: false
