name: build
on: workflow_dispatch

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install pydocbrowser
        run: python -m pip install wheel setuptools git+https://github.com/tristanlatr/pydocbrowser.git
      
      - name: Setup pydocbrowser config
        run: | 
          curl https://raw.githubusercontent.com/tristanlatr/pydocbrowser/main/packages.toml > packages.toml
          curl https://raw.githubusercontent.com/tristanlatr/pydocbrowser/main/README.md > README.md

      - name: Build
        run: python -m pydocbrowser

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: build
          destination_dir: build
          publish_branch: 'main'
          user_name: 'Github Actions'
          user_email: "actions@github.com"
          commit_message: "build"
          enable_jekyll: false